"""Markdown report generator for daily, weekly, position, and strategy reports.

All file operations are wrapped in try/except so a reporting failure
never crashes the scheduler.
"""

import logging
from datetime import date, datetime
from pathlib import Path

from config import settings

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Writes all markdown reports under ``settings.REPORTS_DIR``."""

    def __init__(self) -> None:
        self.reports_dir: Path = settings.REPORTS_DIR
        self.today_path: Path = (
            self.reports_dir / "daily" / f"{date.today().isoformat()}.md"
        )

    # ── helpers ──────────────────────────────────────────────

    def _ensure_parents(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)

    def _append(self, path: Path, text: str) -> None:
        """Append *text* to *path*, creating parents if needed."""
        self._ensure_parents(path)
        with open(path, "a", encoding="utf-8") as f:
            f.write(text)
        logger.debug("Appended to %s", path)

    def _write(self, path: Path, text: str) -> None:
        """Write (overwrite) *text* to *path*, creating parents if needed."""
        self._ensure_parents(path)
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        logger.debug("Wrote %s", path)

    @staticmethod
    def _fmt_dollars(value) -> str:
        try:
            return f"${float(value):,.2f}"
        except (TypeError, ValueError):
            return "N/A"

    @staticmethod
    def _fmt_pct(value) -> str:
        try:
            return f"{float(value):.1f}%"
        except (TypeError, ValueError):
            return "N/A"

    # ================================================================
    # Daily Report Methods
    # ================================================================

    def write_header(self, account: dict) -> None:
        """Write (overwrite) the top section of today's daily report."""
        try:
            value = self._fmt_dollars(account.get("portfolio_value"))
            bp = self._fmt_dollars(account.get("buying_power"))
            positions = account.get("open_positions", 0)
            level = account.get("options_trading_level", "N/A")
            mode = "paper" if settings.ALPACA_PAPER else "live"

            text = (
                f"# Daily Report — {date.today().isoformat()}\n\n"
                f"*Generated by trade-pilot | Strategy: Wheel | Account: {mode}*\n\n"
                "## Account Summary\n\n"
                "| Metric | Value |\n"
                "|--------|-------|\n"
                f"| Portfolio Value | {value} |\n"
                f"| Buying Power | {bp} |\n"
                f"| Open Positions | {positions} |\n"
                f"| Options Trading Level | {level} |\n\n"
            )
            self._write(self.today_path, text)
        except Exception:
            logger.exception("Failed to write daily report header")

    def append_market_conditions(self, macro: dict) -> None:
        """Append the macro / market-conditions section."""
        try:
            vix = macro.get("vix")
            vix_str = f"{vix:.1f}" if vix is not None else "N/A"
            regime = macro.get("vix_regime", "—")

            fg_score = macro.get("fear_greed_score")
            fg_str = f"{fg_score:.0f}" if fg_score is not None else "N/A"
            fg_rating = macro.get("fear_greed_rating", "—")

            rfr = macro.get("risk_free_rate")
            rfr_str = f"{rfr * 100:.2f}%" if rfr is not None else "N/A"

            text = (
                "## Market Conditions\n\n"
                "| Indicator | Value | Signal |\n"
                "|-----------|-------|--------|\n"
                f"| VIX | {vix_str} | {regime} |\n"
                f"| Fear & Greed | {fg_str} | {fg_rating} |\n"
                f"| Risk-Free Rate | {rfr_str} | — |\n\n"
            )
            self._append(self.today_path, text)
        except Exception:
            logger.exception("Failed to append market conditions")

    def append_pre_market_briefing(self, symbol_summaries: list[dict]) -> None:
        """Append the pre-market briefing table.

        Each dict in *symbol_summaries* should contain:
            symbol, days_to_earnings, trend, rsi, iv_rank,
            sma_50_above (bool), sma_200_above (bool).
        """
        try:
            rows: list[str] = []
            for s in symbol_summaries:
                symbol = s.get("symbol", "?")
                dte = s.get("days_to_earnings")
                dte_str = f"{dte}d" if dte is not None else "N/A"
                trend = s.get("trend", "—")
                rsi = s.get("rsi")
                rsi_str = f"{rsi:.0f}" if rsi is not None else "—"
                iv_rank = s.get("iv_rank")
                iv_str = f"{iv_rank:.0f}" if iv_rank is not None else "—"

                # Flag logic
                if dte is not None and dte < 7:
                    flag = "❌ Earnings < 7d"
                elif s.get("sma_50_above") is False and s.get("sma_200_above") is False:
                    flag = "❌ Below both SMAs"
                elif dte is not None and dte < 21:
                    flag = "⚠️ Earnings soon"
                elif rsi is not None and (rsi > 75 or rsi < 25):
                    flag = "⚠️ RSI extreme"
                else:
                    flag = "✅ Watchable"

                rows.append(
                    f"| {symbol} | {dte_str} | {trend} | {rsi_str} "
                    f"| {iv_str} | {flag} |"
                )

            table_body = "\n".join(rows)
            text = (
                "## Pre-Market Briefing\n\n"
                "| Symbol | Earnings | Trend | RSI | IV Rank | Note |\n"
                "|--------|----------|-------|-----|---------|------|\n"
                f"{table_body}\n\n"
            )
            self._append(self.today_path, text)
        except Exception:
            logger.exception("Failed to append pre-market briefing")

    def append_decision(
        self,
        symbol: str,
        state: str,
        decision: dict,
        fill_price: float | None = None,
    ) -> None:
        """Append one decision block to today's report."""
        try:
            now_str = datetime.now().strftime("%I:%M %p ET")
            action = decision.get("action", "unknown").upper()
            contract = decision.get("symbol") or "N/A"
            limit = decision.get("limit_price")
            limit_str = self._fmt_dollars(limit) if limit is not None else "N/A"
            fill_str = self._fmt_dollars(fill_price) if fill_price is not None else "Pending"
            confidence = decision.get("confidence", "N/A")

            # Optional enrichment fields
            delta = decision.get("delta", "—")
            dte = decision.get("dte", "—")
            iv_rank = decision.get("iv_rank", "—")

            # Reasoning sub-fields
            reasoning = decision.get("reasoning", "")
            if isinstance(reasoning, dict):
                macro_r = reasoning.get("macro", "—")
                tech_r = reasoning.get("technical", "—")
                select_r = reasoning.get("selection", "—")
            else:
                macro_r = "—"
                tech_r = "—"
                select_r = str(reasoning) if reasoning else "—"

            # Status
            status_raw = decision.get("status", "")
            if status_raw == "executed" or fill_price is not None:
                status = "✅ Executed"
            elif status_raw == "skipped" or action == "SKIP":
                status = "⏭️ Skipped"
            elif status_raw == "dry_run" or settings.DRY_RUN:
                status = "🔄 Dry Run"
            else:
                status = "✅ Executed"

            text = (
                f"### {now_str} — {symbol} ({state})\n\n"
                f"**Action:** {action}  \n"
                f"**Contract:** {contract}  \n"
                f"**Limit Price:** {limit_str} | **Fill:** {fill_str}  \n"
                f"**Delta:** {delta} | **DTE:** {dte} | **IV Rank:** {iv_rank}  \n"
                f"**Confidence:** {confidence}  \n\n"
                f"> **Macro:** {macro_r}  \n"
                f"> **Technical:** {tech_r}  \n"
                f"> **Selection:** {select_r}  \n\n"
                f"**Status:** {status}\n\n---\n\n"
            )
            self._append(self.today_path, text)
        except Exception:
            logger.exception("Failed to append decision for %s", symbol)

    def append_position_snapshot(self, positions: list[dict]) -> None:
        """Append a table of current open positions."""
        try:
            now_str = datetime.now().strftime("%I:%M %p ET")
            rows: list[str] = []
            for p in positions:
                sym = p.get("symbol", "?")
                opt_type = p.get("option_type", "—")
                strike = p.get("strike_price")
                strike_str = self._fmt_dollars(strike) if strike is not None else "—"
                expiry = p.get("expiration_date", "—")
                dte = p.get("dte", "—")
                delta = p.get("delta", "—")
                entry = p.get("avg_entry_price")
                entry_str = self._fmt_dollars(entry) if entry is not None else "—"
                current = p.get("current_price")
                current_str = self._fmt_dollars(current) if current is not None else "—"
                pnl = p.get("unrealized_pl")
                pnl_str = self._fmt_dollars(pnl) if pnl is not None else "—"

                rows.append(
                    f"| {sym} | {opt_type} | {strike_str} | {expiry} "
                    f"| {dte} | {delta} | {entry_str} | {current_str} | {pnl_str} |"
                )

            table_body = "\n".join(rows) if rows else "| — | — | — | — | — | — | — | — | — |"
            text = (
                f"## Open Positions — {now_str}\n\n"
                "| Symbol | Type | Strike | Expiry | DTE | Delta "
                "| Entry | Current | P&L |\n"
                "|--------|------|--------|--------|-----|-------"
                "|-------|---------|-----|\n"
                f"{table_body}\n\n"
            )
            self._append(self.today_path, text)
        except Exception:
            logger.exception("Failed to append position snapshot")

    def append_eod_summary(self, metrics: dict) -> None:
        """Append end-of-day summary with P&L and NTA events."""
        try:
            pnl = self._fmt_dollars(metrics.get("day_pnl"))
            executed = metrics.get("trades_executed", 0)
            skipped = metrics.get("trades_skipped", 0)
            premium = self._fmt_dollars(metrics.get("premium_collected"))

            nta_events = metrics.get("nta_events", [])
            if nta_events:
                nta_lines = "\n".join(f"- {e}" for e in nta_events)
            else:
                nta_lines = "None"

            text = (
                "## End of Day Summary\n\n"
                "| Metric | Value |\n"
                "|--------|-------|\n"
                f"| Day P&L | {pnl} |\n"
                f"| Trades Executed | {executed} |\n"
                f"| Trades Skipped | {skipped} |\n"
                f"| Premium Collected | {premium} |\n\n"
                "### NTA Events Today\n\n"
                f"{nta_lines}\n\n"
            )
            self._append(self.today_path, text)
        except Exception:
            logger.exception("Failed to append EOD summary")

    # ================================================================
    # Weekly Report
    # ================================================================

    def write_weekly_report(
        self,
        week_metrics: dict,
        daily_reports: list[str],
    ) -> Path | None:
        """Create ``reports/weekly/YYYY-WNN.md`` and return its path."""
        try:
            now = datetime.now()
            iso_year, iso_week, _ = now.isocalendar()
            filename = f"{iso_year}-W{iso_week:02d}.md"
            path = self.reports_dir / "weekly" / filename

            # This-week metrics
            tw = week_metrics.get("this_week", {})
            at = week_metrics.get("all_time", {})

            def _row(label: str, tw_val, at_val) -> str:
                return f"| {label} | {tw_val} | {at_val} |"

            perf_rows = "\n".join([
                _row("Trades Placed",
                     tw.get("trades", 0), at.get("trades", 0)),
                _row("Win Rate",
                     self._fmt_pct(tw.get("win_rate")),
                     self._fmt_pct(at.get("win_rate"))),
                _row("Premium Collected",
                     self._fmt_dollars(tw.get("premium")),
                     self._fmt_dollars(at.get("premium"))),
                _row("Realized P&L",
                     self._fmt_dollars(tw.get("pnl")),
                     self._fmt_dollars(at.get("pnl"))),
                _row("Assignments",
                     tw.get("assignments", 0), at.get("assignments", 0)),
                _row("Rolls",
                     tw.get("rolls", 0), at.get("rolls", 0)),
                _row("Avg Hold Time",
                     f"{tw.get('avg_hold', 0):.1f}d",
                     f"{at.get('avg_hold', 0):.1f}d"),
            ])

            # Per-symbol breakdown
            symbol_rows_list: list[str] = []
            for sd in week_metrics.get("by_symbol", []):
                symbol_rows_list.append(
                    f"| {sd.get('symbol', '?')} "
                    f"| {sd.get('trades', 0)} "
                    f"| {self._fmt_pct(sd.get('win_rate'))} "
                    f"| {self._fmt_dollars(sd.get('premium'))} "
                    f"| {self._fmt_dollars(sd.get('pnl'))} |"
                )
            symbol_rows = "\n".join(symbol_rows_list) if symbol_rows_list else "| — | — | — | — | — |"

            # Skip analysis
            skip_reasons = week_metrics.get("skip_reasons", [])
            if skip_reasons:
                skip_lines = "\n".join(
                    f"{i}. {r.get('reason', '?')} ({r.get('count', 0)}x)"
                    for i, r in enumerate(skip_reasons, 1)
                )
            else:
                skip_lines = "No skips this week."

            # Notable events
            notable = week_metrics.get("notable_events", [])
            if notable:
                notable_lines = "\n".join(f"- {e}" for e in notable)
            else:
                notable_lines = "No notable events."

            # Daily summaries
            if daily_reports:
                daily_section = "\n\n".join(daily_reports)
            else:
                daily_section = "No daily reports available."

            date_range = week_metrics.get("date_range", "")

            text = (
                f"# Weekly Report — Week {iso_week:02d}, {iso_year}\n\n"
                f"*{date_range}*\n\n"
                "## Performance Summary\n\n"
                "| Metric | This Week | All Time |\n"
                "|--------|-----------|----------|\n"
                f"{perf_rows}\n\n"
                "## Decisions by Symbol\n\n"
                "| Symbol | Trades | Win Rate | Premium | P&L |\n"
                "|--------|--------|----------|---------|-----|\n"
                f"{symbol_rows}\n\n"
                "## Skip Analysis\n\n"
                "Top reasons Claude skipped trades this week:\n\n"
                f"{skip_lines}\n\n"
                "## Notable Events\n\n"
                f"{notable_lines}\n\n"
                "## Daily Summaries\n\n"
                f"{daily_section}\n"
            )
            self._write(path, text)
            return path
        except Exception:
            logger.exception("Failed to write weekly report")
            return None

    # ================================================================
    # Positions Report
    # ================================================================

    def write_current_positions(
        self,
        positions: list[dict],
        account: dict,
    ) -> None:
        """Overwrite ``reports/positions/current.md`` with a live snapshot."""
        try:
            path = self.reports_dir / "positions" / "current.md"
            now_str = datetime.now().strftime("%Y-%m-%d %I:%M %p ET")
            value = self._fmt_dollars(account.get("portfolio_value"))
            bp = self._fmt_dollars(account.get("buying_power"))

            # Options positions table
            pos_rows: list[str] = []
            for p in positions:
                sym = p.get("symbol", "?")
                opt_type = p.get("option_type", "—")
                strike = p.get("strike_price")
                strike_str = self._fmt_dollars(strike) if strike is not None else "—"
                expiry = p.get("expiration_date", "—")
                dte = p.get("dte", "—")
                delta = p.get("delta", "—")
                entry = p.get("avg_entry_price")
                entry_str = self._fmt_dollars(entry) if entry is not None else "—"
                current = p.get("current_price")
                current_str = self._fmt_dollars(current) if current is not None else "—"
                pnl = p.get("unrealized_pl")
                pnl_str = self._fmt_dollars(pnl) if pnl is not None else "—"

                pos_rows.append(
                    f"| {sym} | {opt_type} | {strike_str} | {expiry} "
                    f"| {dte} | {delta} | {entry_str} | {current_str} | {pnl_str} |"
                )

            pos_body = "\n".join(pos_rows) if pos_rows else "| — | — | — | — | — | — | — | — | — |"

            # Wheel state per symbol
            wheel_rows: list[str] = []
            for p in positions:
                sym = p.get("underlying", p.get("symbol", "?"))
                state = p.get("wheel_state", "—")
                since = p.get("state_since", "—")
                notes = p.get("notes", "")
                wheel_rows.append(f"| {sym} | {state} | {since} | {notes} |")

            wheel_body = "\n".join(wheel_rows) if wheel_rows else "| — | — | — | — |"

            text = (
                "# Current Positions\n\n"
                f"*Last updated: {now_str}*\n\n"
                "## Account\n\n"
                f"Portfolio: {value} | Buying Power: {bp}\n\n"
                "## Open Options Positions\n\n"
                "| Symbol | Type | Strike | Expiry | DTE | Delta "
                "| Entry | Current | P&L |\n"
                "|--------|------|--------|--------|-----|-------"
                "|-------|---------|-----|\n"
                f"{pos_body}\n\n"
                "## Wheel State Per Symbol\n\n"
                "| Symbol | State | Since | Notes |\n"
                "|--------|-------|-------|-------|\n"
                f"{wheel_body}\n"
            )
            self._write(path, text)
        except Exception:
            logger.exception("Failed to write current positions report")

    # ================================================================
    # Strategy Comparison
    # ================================================================

    def write_strategy_comparison(self, strategies: list[dict]) -> None:
        """Overwrite ``reports/strategies/comparison.md``.

        *strategies* is a list of dicts, each representing one strategy.
        Currently only "Wheel (Paper)" is expected; the table is designed
        to accept additional strategies later.
        """
        try:
            path = self.reports_dir / "strategies" / "comparison.md"
            today_str = date.today().isoformat()

            # Build header row dynamically from strategy names
            names = [s.get("name", "?") for s in strategies]
            header = "| Metric | " + " | ".join(names) + " |"
            sep = "|--------|" + "|".join(["--------"] * len(names)) + "|"

            metric_keys = [
                ("Account Value", "account_value", self._fmt_dollars),
                ("Total Return", "total_return", self._fmt_pct),
                ("Win Rate", "win_rate", self._fmt_pct),
                ("Sharpe (approx)", "sharpe", lambda v: f"{float(v):.2f}" if v is not None else "N/A"),
                ("Open Positions", "open_positions", lambda v: str(v) if v is not None else "0"),
                ("Trades This Month", "trades_this_month", lambda v: str(v) if v is not None else "0"),
            ]

            rows: list[str] = []
            for label, key, fmt in metric_keys:
                cells = []
                for s in strategies:
                    val = s.get(key)
                    try:
                        cells.append(fmt(val))
                    except (TypeError, ValueError):
                        cells.append("N/A")
                rows.append(f"| {label} | " + " | ".join(cells) + " |")

            table = "\n".join(rows)

            text = (
                "# Strategy Comparison\n\n"
                f"*Last updated: {today_str}*\n\n"
                f"{header}\n{sep}\n{table}\n"
            )
            self._write(path, text)
        except Exception:
            logger.exception("Failed to write strategy comparison")
